dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
git:
  depth: 3
cache:
  directories:
  - "$HOME/.m2"
before_install:
  - git clone https://github.com/CJSCommonPlatform/travis-settings.git target/travis-settings
  - ln -sfT ${PWD}/target/travis-settings/settings.xml ${HOME}/.m2/settings.xml
install: "${PWD}/target/travis-settings/java/install.sh -DexcludeGroupIds=uk.gov.justice.service,uk.gov.justice.services"
script: "${PWD}/target/travis-settings/java/script-install.sh coveralls:report"
after_success: "${PWD}/target/travis-settings/java/after_success.sh"
env:
  global:
  - secure: D9ZYTSFI+HWlKt2rMfL1jFbSA0qJnJrjFXhTQFnPM58KlsxCmBSN10FJ0ZuVZSfR4N5mcNfUBxkPQ9eHBa9m/4vCjfCpDhpacnecSXTvMNwSDGXhn8E/1Q1FlC7yeN7FLhTSCC32J32Ar6ho4fYAEAgNJ0DC50i/ARL+4TsVYyFrISDi7ol7KLccPBmNjxC07EHI1Vbke3RWzu0XoDmdIe3R257k+4WgZwEIX87VmoSsfe52/1CbzuC0LoGpQi9Hq0hfhBUUWTDyHKajk0v3nu9jku21nCoYPwAh/LM5enYJKPqZuLuGFjBwRH4pg/VxLi7jz9phWTP3kyFpMzDmBXktFa/HEuzUprrSOdGvzGiPltJgVo3zeAJYgpICNJDIttJDzLHNV/+lqcTAapKS72qeUq9mrGNJJI1tnslmfGiAE2/7JSkH50/s8XbvrH0lK+gZn2UnrXCfgUXrTRWdcCozltQCmN9KCHgoxejMF+n8lDXs74vWD0OTp+AnusjJZV+d7UwzQ8kz0uALr9fO2JEgXUbFw9/3kPYzjkA5QV/BC/0n254XPAFb5jaVzHKiWa9PrDr8ZHNozW0UdUUEQ013Mlv/owIxCHzdiQOJKQKJH3czX5d2YwPyBmfDWVwbEezR3T0V8uu2It+sitTUDFKgAc8fCi671C36F62EeXA=
  - secure: LWIUXv+6sYvfnE/pgWztaP8/1GUV0yGu21awPqTF2X1zc8dQWb3/oO7x6rJhNhnf6T9In0smp43lH0KCx4mCblq/dGo1E40aEW6RVMoSxnQHc3352phWkL8xjsToINnObGDSopaOTj6c0oKWiB8pjBMd1c1AU+JOWopTzWOzIyZX6y+PMEvE1GNhAA5pbySZQsymbCu9+920JmOgX025K8fvGnQM6Vn8uG0K55VOgXA/zgYUn0Y2+hD2anactmhOUcRlVyJHL7RCzc+6KgsxJQma+sBDKSBXQFmf5oU9IA7kQWFW7od7wNnmhxJkuH7rEphpm2u3fup2pe/FAl9S1K0v95sh0ZY+yU8b7m5SS7UNpkKsmJizZsnRwUbD0gi4srWE3qxou+OdNwfVrFRiy4Vj6MlAHGnHQM1q6u6gGiTMwhpNJuq0My7xd58yKnlv4pmR733FXoWpQVrFB408XVeF96VL/Evd9R2bzLtxMn0/jwtblByVMDI7DVY0PcxePKyMSPhyq7C0pFMQk8sVNiZr48sRAw59j+3QdUXjVKgWYs0Cq1eq87gGk8VkWQXhuwv7gJZ79M6nRQkW+xnPT2pqoupK4pxxCzur8aZ/oj03koke7VjgL7bJRFyMg2L++C0No6BljMfqihvQ1h/vphaODYbHW4CZlSx4fWhHPro=
